### ISSUE TITLE
Untracked setup.sh file can lead to inadvertent commits

### ISSUE THREAD

**Issue by Exarchias** [emrgnt-cmplxty/Automata#114]
**Describe the bug**
The current setup instructions involve creating and modifying a setup.sh file based on an example file. However, the setup.sh file is not included in the .gitignore, which means it appears as an untracked file in the Git status. This could potentially lead to the inadvertent addition and commit of this file, which could be problematic as it contains sensitive information such as API keys.

I had posted a short message about this in the project's Discord channel, but it appears to have gone unnoticed, likely due to the relatively low traffic in the channel currently. I opted not to send a direct message regarding the issue, as I prefer to address it through the proper channels.

**To Reproduce**
1. Follow the current setup instructions which include creating a setup.sh file.
2. Run git status.

**Expected behavior**
The setup.sh file should not appear in the list of untracked files.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 11
 - Github Desktop / Git on CMD

**Additional context**
**Actual behavior:** 
The setup.sh file appears in the list of untracked files.

**Proposed Solution:** 
I would be more than willing to tackle this issue myself. I propose to add setup.sh to the .gitignore file to prevent it from being tracked by Git. This would also give me the chance to practice contributing to the project.

**Comment by emrgnt-cmplxty** [comment]
Thank you for sharing this suggestion! This seems like a good idea and could be implemented in a straightforward enough manner. Would you mind creating a PR for review?

**Comment by Exarchias** [comment]
Hi Owen,

Thank you for your prompt response and for taking the time to review my suggestion. I'm pleased to hear that you find the idea useful. I will definitely create a PR for this matter shortly.

Also, thank you for the additional changes for the setup.sh file to accommodate mac OS. I appreciate your continuous efforts to enhance the portability and user experience of the project. I'll make sure to review the changes you made in PR #115.

Best regards,
Robert

**Comment by Exarchias** [comment]
Dear @emrgnt-cmplxty , 

As discussed, I have created a Pull Request addressing this issue. You can find it at this link: [https://github.com/emrgnt-cmplxty/Automata/pull/116](https://github.com/emrgnt-cmplxty/Automata/pull/116). 

I have added `setup.sh` to the `.gitignore` file to prevent its accidental inclusion in the repository. Feel free to review the changes and suggest any necessary adjustments.

Best regards,
Robert
