### ISSUE TITLE
Improve "contributing.md" to include more detailed instructions for contributors

### ISSUE THREAD

**Issue by Exarchias** [emrgnt-cmplxty/automata#180]
The current `contributing.md` provides a basic framework for contributions, but there are opportunities to enhance it and make it more helpful to contributors.

Here are the proposed enhancements:

1. **Setting up the project locally:** Include detailed instructions about how to clone the repo, install the dependencies, and run the project.

2. **Creating an Issue:** Provide guidelines on how to correctly create an issue. The instructions should emphasize on providing a clear title, a detailed description of the problem or the feature request, and selecting the appropriate labels.

3. **Creating a Pull Request:** Outline the process of creating a PR. Encourage contributors to create a new branch for each PR. Provide instructions on how to fetch and pull the latest changes from the main branch before pushing their changes.

4. **Commit Message Guidelines:** Introduce the concept of conventional commits and explain why they are important. Include a link to a detailed guide for contributors who want to learn more about it.

By incorporating these enhancements, we can make the process of contributing to Automata more streamlined and efficient, thereby attracting more valuable contributions from the open-source community.

**Comment by wwzeng1** [comment]
Hi! I’m one of the founders of Sweep, a github app that solves issues(like updating documentation) by writing pull requests. 
This looks like a good issue for Sweep https://github.com/sweepai/sweep to try. We have onboarding [instructions here](https://github.com/sweepai/sweep/blob/main/README.md#-getting-started), I’m also happy to help you onboard directly :)

**Comment by emrgnt-cmplxty** [comment]
These changes look good, @Exarchias. Want to go ahead and submit a PR?

**Comment by wwzeng1** [comment]
@Exarchias @emrgnt-cmplxty I created a first go here: https://github.com/wwzeng1/automata/issues/1
https://github.com/wwzeng1/automata/pull/4

**Comment by Exarchias** [comment]
> These changes look good, @Exarchias. Want to go ahead and submit a PR?

Hey @emrgnt-cmplxty. I will go for it :)

**Comment by Exarchias** [comment]
Hello @wwzeng1, you have an intriguing project and I appreciate the idea. In fact, I believe that we are attempting to achieve something similar here. However, there are a few minor issues at present. It appears the system wasn't sure where to direct its efforts and there were a couple of mistakes; it seems this issue could benefit from a bit of human intervention. Furthermore, before incorporating your system, we need to review it in terms of its license and usage terms, and have a detailed discussion about it.

For the time being, I will create a separate PR for this issue and handle it manually. This will give us all the necessary time to review your project and discuss the potential of utilizing your software.

Does my approach sound reasonable, @emrgnt-cmplxty ?

With my best regards,
Robert

**Comment by wwzeng1** [comment]
We have a web app that seems to do exactly what you mentioned :) Happy to share our terms of service/hop on a call for this. Here's my calendly https://calendly.com/william-ok0/introductory-call?month=2023-07
https://github.com/sweepai/sweep#-sweep-github-app

**Comment by Exarchias** [comment]
> We have a web app that seems to do exactly what you mentioned :) Happy to share our terms of service/hop on a call for this. Here's my calendly https://calendly.com/william-ok0/introductory-call?month=2023-07 https://github.com/sweepai/sweep#-sweep-github-app

Excellent project @wwzeng1 ! Thank you, for bring it to our attention, and we have a good look at it! :)
