### ISSUE TITLE
Expanding Dockerfile with SCIP-Python and Indexing Scripts

### ISSUE THREAD

**Issue by Exarchias** [emrgnt-cmplxty/automata#398]
**Is your feature request related to a problem? Please describe.**
The current Dockerfile configuration could benefit from a more expansive setup. It doesn't include SCIP-Python or various indexing scripts which are frequently used in our development workflow.

**Describe the solution you'd like**
I propose expanding our Dockerfile to include the installation and execution of SCIP-Python, which is crucial for code analysis. 

Also, it would be beneficial to have the following indexing scripts run when the Docker container is initialized:

```
# Install dependencies and run indexing on the local codebase
automata install-indexing

# Refresh the code embeddings (after making local changes)
poetry run automata run-code-embedding

# Refresh the documentation + embeddings
poetry run automata run-doc-embedding --embedding-level=2
```

However, to include these, we'll need to find a graceful solution for running `automata configure`, which sets up the environment and configuration files.

**Describe alternatives you've considered**
N/A. This issue is focused on expanding the Dockerfile to improve our development and testing environments.

**Additional context**
I am ready to work on this task and am considering aiming for Codacy compliance in this PR, although it is not a hard requirement for this task's success.

**Comment by NolanTrem** [comment]
> Also, it would be beneficial to have the following indexing scripts run when the Docker container is initialized

This would be a really nice feature, the only thing that we have to remember is that we'd need to have already run `automata configure` or set API keys for some of these commands. I think that expanding the Docker is a really awesome next step, since it seems to be getting used 😄

**Comment by emrgnt-cmplxty** [comment]
Thank you for making this issue, @Exarchias. I agree w/ Nolan's feedback above. I suggest you two continue to spec it out together, as Nolan has taken the lead on docker related matters.
